name: Generate CHANGELOG

on:
  push:
    tags:
      - 'v*'

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate CHANGELOG
        run: |
          npx standard-version --skip.commit --skip.tag --release-as ${{ github.ref_name }}
          git add CHANGELOG.md
          git commit -m "chore: update changelog"
          git push